### ISSUE TITLE
about the snakemake doesn't work

### ISSUE THREAD

**Issue by yanzhongsino** [jlanga/smsk_popoolation#17]
Hi, thank you for your contributions!
While I want to install smsk_popoolation after installing anaconda3, I met an issue like the following.
git clone https://github.com/jlanga/smsk_popoolation.git smsk_popoolation #run well
cd smsk_popoolation # run well
snakemake --use-conda --create-envs-only #dont't work and get the message

The program 'snakemake' is currently not installed. To run 'snakemake' please ask your administrator to install the package 'snakemake'.

so I need install 'snakemake' before using snakemake or 'snakemaker' is a script of 'smsk_popoolation'?

Any reply will be welcomed.

**Comment by jlanga** [comment]
Hi @yanzhongsino.

You need to install `snakemake` first. I recommend to do it through conda:

```
conda install snakemake
```

Cheers
