### ISSUE TITLE
use-envs-only problem

### ISSUE THREAD

**Issue by azurillandfriend** [jlanga/smsk_popoolation#18]
This may be due to an update in snakemake commands. When I tried to paste the command from the instructions "snakemake --use-conda --create-envs-only" I got the error message "snakemake: error: unrecognized arguments: --create-envs-only"
First I tried replacing with snakemake --use-conda --conda-create-envs-only but I got the following error message asking me to enter the number of cores (Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -cN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -c1.)
I then tried replacing with "snakemake --use-conda --conda-create-envs-only --cores 24" This seems to run as far as "Building DAG of jobs...
Creating conda environment src/snakefiles/hp.yml...
Downloading and installing remote packages."
Although this is taking rather a long time (> 5 minutes) so there may still be an issue.

**Comment by jlanga** [comment]
Hi Naomi.

Snakemake has been under heavy development in the latter months. I have to update the readme files for all my projects.

The issue with the download has to do with conda, which is terribly slow when getting packages from conda-forge and bioconda. By installing `mamba` (`conda install -c conda-forge mamba`) the speed improves drastically. Snakemake will notice that mamba is there. Nonetheless, it will take 5 mins or so.

**Comment by azurillandfriend** [comment]
thanks, I'll use mamba next time!
