### ISSUE TITLE
error in rule "raw_extract_genome"

### ISSUE THREAD

**Issue by azurillandfriend** [jlanga/smsk_popoolation#19]
Working through the example data, I ran using "snakemake --use-conda --cores 24"
However, I got an error in rule "raw_extract_genome" that the 2R.fa.gz file (supplied example data) is not in gzip format. Is it the example data or the command at fault?

**Comment by jlanga** [comment]
Hi Naomi. I've checked in my laptop and it must be an issue with Git LFS. I use that to track large files (genomes, fastq files, etc). To install it type in the command line `git lfs install` in any directory. Then, remove and clone again the repo.

**Comment by azurillandfriend** [comment]
thanks, will do
