### ISSUE TITLE
use-envs-only problem / ModuleNotFoundError in line 3 of /home/*/smsk_popoolation/workflow/Snakefile: No module named 'pandas'

### ISSUE THREAD

**Issue by Adam-Staniszewski** [jlanga/smsk_popoolation#28]
Hi,

I went through all the past issue and hit the same problems as previous users.

/smsk_popoolation$ snakemake --conda-create-envs-only
Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -cN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -c1.

When I go with certain number of cpus or --cores all always get following error:

ModuleNotFoundError in line 3 of /home/*/smsk_popoolation/workflow/Snakefile:
No module named 'pandas'

I tried to work it around by installing pandas in the env or  adding pandas to dependencies in smsk_popoolation/workflow/rules/helpers/__environment__.yml, nothing changed, same error with pandas occurs

Could you update documentation to workable version ?

Thank you

**Comment by jlanga** [comment]
Hi @Adam-Staniszewski.

The module that you use to load snakemake doesn't come with pandas. It must be way too old. Snakemake has been forcing the installation of pandas for a while.  It is one of many mandatory dependencies. In conda it is installed out of the box: https://bioconda.github.io/recipes/snakemake/README.html

Make sure that you are using snakemake 8, and if you are using modules, that the other dependencies are there too.

Kind regards,

Jorge
